# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.command:
        class: AppBundle\Admin\CommandAdmin
        arguments: [~, AppBundle\Entity\Command, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Command }
